title: Developer Handbook
lang: en
description: A developers handbook

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-avatar
# - jemoji
# - jekyll-mentions